import '@/assets/styles/global.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import AppWrap from '@/components/app-wrap';
import { dir } from 'i18next';
import { Languages } from '@/i18n';
import { CommonPageProps } from '@/interfaces';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return Languages.map((lng) => ({ lng }));
}

export default function RootLayout({ children, params: { lng } }: CommonPageProps) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <head>
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src="https://cdn.jsdelivr.net/npm/systemjs@6.14.1/dist/system.min.js" />
      </head>
      <body className={`${inter.className} cp-scrollbar cp-scrollbar_fixed`} suppressHydrationWarning>
        <AppWrap>{children}</AppWrap>
      </body>
    </html>
  );
}
